|ERROR|2018-05-12 10:58:12,035|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526093816640-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x105c6de10>: Failed to establish a new connection: [Errno 60] Operation timed out',)).
|ERROR|2018-05-12 10:58:39,848|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526093918755-0 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))).
|ERROR|2018-05-12 10:59:06,036|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526093945006-0 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))).
|ERROR|2018-05-12 10:59:35,869|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526093974685-0 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))).
|ERROR|2018-05-12 11:01:04,619|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526094063546-0 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))).
|ERROR|2018-05-12 11:03:57,433|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526094161041-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x112acde48>: Failed to establish a new connection: [Errno 60] Operation timed out',)).
|ERROR|2018-05-12 11:52:01,252|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526097041824-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1127bde10>: Failed to establish a new connection: [Errno 60] Operation timed out',)).
|ERROR|2018-05-12 16:25:35,686|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526113460086-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x109920e48>: Failed to establish a new connection: [Errno 60] Operation timed out',)).
|ERROR|2018-05-12 18:57:18,130|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526122562745-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10a4d3eb8>: Failed to establish a new connection: [Errno 60] Operation timed out',)).
|ERROR|2018-05-12 23:18:56,222|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526138334414-0 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',))).
|ERROR|2018-05-13 07:54:54,315|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526169219090-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ddbbe48>: Failed to establish a new connection: [Errno 60] Operation timed out',)).
|ERROR|2018-05-13 10:36:00,417|Server reports an error: {'executed': False, 'error': 'Unauthorized'}.
|ERROR|2018-05-14 07:24:22,068|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526253786972-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10af7be80>: Failed to establish a new connection: [Errno 60] Operation timed out',)).
|ERROR|2018-05-14 22:54:54,863|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526309694838-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107dc7e80>: Failed to establish a new connection: [Errno 61] Connection refused',)).
|ERROR|2018-05-14 22:55:00,060|Socket returns an error: HTTPSConnectionPool(host='api-demo.fxcm.com', port=443): Max retries exceeded with url: /socket.io/?access_token=08ed0b29eeb68fd2adc4676e67a8973c982f74ac&agent=pythonquants&EIO=3&transport=polling&t=1526309700035-0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10b81cef0>: Failed to establish a new connection: [Errno 61] Connection refused',)).
